services:

  gateway:
    build: gateway/.
    container_name: gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      book-app-network:
        ipv4_address: 100.0.0.2

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    restart: unless-stopped
    ports:
      - "8500:8500"
    networks:
      book-app-network:
        ipv4_address: 100.0.0.3

  config:
    build: config/.
    container_name: config
    restart: unless-stopped
    networks:
      book-app-network:
        ipv4_address: 100.0.0.4

  user-db:
    image: postgres:latest
    container_name: user-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: administration
    networks:
      book-app-network:
        ipv4_address: 100.0.0.5

  user-service:
    build: user/.
    container_name: user-service
    restart: unless-stopped
    networks:
      book-app-network:
    depends_on:
      - config
      - consul
      - user-db

  mongodb:
    image: mongo:4
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      book-app-network:
        ipv4_address: 100.0.0.6

  image-service:
    build: image/.
    container_name: image-service
    restart: unless-stopped
    networks:
      book-app-network:
    depends_on:
      - config
      - consul
      - mongodb

  book-db:
    image: postgres:latest
    container_name: book-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: books
    networks:
      book-app-network:
        ipv4_address: 100.0.0.7

  book-service:
    build: book/.
    container_name: book-service
    restart: unless-stopped
    networks:
      book-app-network:
    depends_on:
      - consul
      - config
      - book-db

networks:

  book-app-network:
    name: book-app-network
    driver: bridge
    ipam:
      config:
        - subnet: 100.0.0.0/24