services:

  gateway:
    build: gateway/.
    container_name: gateway
    networks:
      book-app-network:
        - ipv4_address: 100.0.0.2

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      book-app-network:
        ipv4_address: 100.0.0.3

  config:
    build: config/.
    container_name: config
    networks:
      book-app-network:
        ipv4_address: 100.0.0.4


networks:

  book-app-network:
    name: book-app-network
    driver: bridge
    ipam:
      config:
        - subnet: 100.0.0.0/24