spring.application.name=image-service

spring.data.mongodb.uri=mongodb://100.0.0.6:27017/images
spring.data.mongodb.database=images

app.placeholder.path=/app/image_placeholder.png
app.content.type.values={'image/webp','image/jpeg','image/png'}

spring.cloud.openfeign.oauth2.enabled=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=10MB
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB
spring.servlet.multipart.location="."