spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:db/changelog.xml

spring.data.mongodb.uri=mongodb://localhost:27017/images

app.page.size=6

app.cache.max-cache-size=10

app.placeholder.path=image_placeholder.png
app.contenttype.values={'image/webp','image/jpeg','image/png'}

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.javax.cache.missing_cache_strategy=create
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=10MB
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB
spring.servlet.multipart.location="."