spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.consul.host=200.45.107.3
spring.cloud.consul.discovery.register=false
spring.cloud.consul.discovery.register-health-check=false

spring.application.name=gateway